### ISSUE TITLE
Discriminator type value output twice in JSON

### ISSUE THREAD

**Issue by mikesir87** [soulwing/prospecto#18]
When creating the JSON view for a ViewTemplate that has a  discriminator, the **type** attribute is output twice.  It appears the first time is where it should, but then it's output when "dipping down" into the subtype specific properties.  The second one also doesn't make use of the specified discriminator strategy.

```java
  ViewTemplate DETAIL_VIEW = ViewTemplateBuilderProducer
      .object(TestObject.class)
        .discriminator(SimpleClassNameDiscriminatorStrategy.class,
            "suffix", "Object", "decapitalize", true)
        .value("id")
        .subtype(SubTestObject.class)
          .value("text")
          .end()
        .build()
```  

The output contains
```json
{
  "type" : "subTest",
  "id": 12345,
  "type": "SubTestObject",
  "text": "Some text"
}
```

**Comment by ceharris** [comment]
Fixed by df00f7c
