### ISSUE TITLE
Add support for arrayOfReferences

### ISSUE THREAD

**Issue by mikesir87** [soulwing/prospecto#24]
We had talked about whether it was needed, but I finally found a use case.

For myself, when I want to create a new registration, I want to specify the products for that registration all in the initial request.  The model might look like this...

```json
{
  "registrant" : {
    "id" : "627ad049-78a6-4c32-aba5-1d46c3a26250"
  },
  "products" : [
    { "id" : "5b04fd96-6e04-4002-b337-7a36e5ff3c8a" },
    { "id" : "6788b798-495f-4b03-a36a-2efc9555f42d" }
  ]
}
```

I have the registrant working by using a reference and the entity reference resolver.  Would be nice to have that same support for the products too.  In the meantime, I can do it as an array of objects and then go back and resolve those manually, so it's not mission critical right now, but does require additional work.

**Comment by ceharris** [comment]
Makes perfect sense.

**Comment by ceharris** [comment]
Add just a couple of basic test cases for this. Seems to do the trick, but might still be some bugs hanging out in it.
