### ISSUE TITLE
Support for enum objects

### ISSUE THREAD

**Issue by mikesir87** [soulwing/prospecto#45]
It would be nice to have an enum represented in an outputted view as both it's name and it's ```toString``` value.  Example:

```java
public enum Animal {
  DOG(4), CAT(4), MONKEY(2);
  private final int numLegs;

 Animal(int numLegs) { this.numLegs = numLegs; }

  public int getNumLegs() {
    return numLegs;
  }

  public String toString() {
    return name().toLowerCase();
  }
}

public class Person {
  private String name;
  private Animal pet;
  // Getters and setters
}
```

(sure... it's just lower-casing, but it's just an example)

Then, in a final view, to have the ability to make something like this...

```java
ViewTemplate PERSON = ViewTemplateProducer
    .object(Person.class)
        .value("name")
        .enum("pet")
            .name("name")
            .displayName("displayName")
            .value("numLegs")
            .end()
        .build();
```

where ```.name()``` is invoking ```name()```, ```displayName``` is the ```toString()```, and ```numLegs``` is invoking the ```getNumLegs()``` method on the enum.  I'm not 100% sold on the ```displayName()``` method name, but couldn't come up with a better name to invoke the ```toString()```.  So, feel free to modify it. ;)

The final JSON output might look like this then...

```json
{
  "name" : "Charlie Brown",
  "pet" : {
    "name" : "DOG",
    "displayName" : "dog",
    "numLegs" : 4
  }
}
```

**Comment by ceharris** [comment]
It'd be nice to get `name` and `displayName` in the view as defaults without having to explicitly include them; maybe those are really just configuration calls on the current node (kinda like `source`).

**Comment by ceharris** [comment]
I think it's going to be this, instead:

```
ViewTemplate PERSON = ViewTemplateProducer
    .object(Person.class)
        .value("name")
        .object("pet", Animal.class)
            .name()
            .displayString()
            .value("numLegs")
            .end()
        .build();
```

`.name` can only be used when the parent node is a subtype of `Enum.class`; it has overloads to allow you to specify the name of the node in the view and the namespace for the name.  The default name of the node is `name`.

`.displayString` can be used in any container node to include the value of `toString` from the corresponding model object.  It has overloads to allow you to specify the name and namespace for the node. The default node name is `displayString`.

**Comment by mikesir87** [comment]
Makes sense.
