### ISSUE TITLE
Unexpected results when swapping between wrapper/primitive types

### ISSUE THREAD

**Issue by mikesir87** [soulwing/prospecto#63]
Given the following model:

```java
class TestModel {
  private Boolean enabled;
  public boolean isEnabled() { return enabled != null && enabled; }
  public void setEnabled(Boolean enabled) { this.enabled = enabled; }
}
```

the following template:

```java
  ViewTemplate TEMPLATE = ViewTemplateBuilderProducer
      .object(TestModel.class)
        .value("enabled")
        .build();
```

and the following JSON:

```json
{ "enabled": false }
```

the value of enabled on the resolved model will be `null`, not `false`.

I traced it down and found that, in the `ReflectionAccessFactory`, the return of `Introspector.getBeanInfo(TestModel.class).getPropertyDescriptors()` does not return both a `readMethod` and a `writeMethod`.

I recognize there may not be much that can be done to fix this, as it's in the underlying Introspector.  But, may not be bad to document somewhere (not sure where?).

**Comment by ceharris** [comment]
Yeah, so by definition of JavaBeans properties, the getter and the setter have to have the same type, and a wrapper type is not the same as the primitive. If the model can be changed, you could add `Boolean getEnabled()` to the same interface and then the introspection should work properly.
